repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer


- repo: local
  hooks:
  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    types: [python]

  - id: flake8
    name: Check with Flake8
    entry: poetry run flake8
    language: system
    pass_filenames: false
    types: [python]
    args: [--count, .]
